### ISSUE TITLE
[Feature Request] Setting for default page zoom (below 100%)

### ISSUE THREAD

**Issue by a60wattfish** [snowhaze/SnowHaze-iOS#12]
A lot of websites are poorly designed for modern smart phones, with hardcoded font sizes for smartphones with 3.5" screens. It means you can't get much information on screen unless you switch the browser to desktop mode.

Safari on iOS lets you get around this by letting you set the default zoom level to 50% and 75% which fixes this issue for me.

Could this be made an option on SnowHaze? I will say that this is obviously something that could be fingerprinted, however the usability increase is pretty high. This could be resolved by having a toggle on the "Create tab with settings" screen.

**Comment by snowhaze** [comment]
We have included a feature in version 3.0 that allows to scale the content webpages. Version 3.0 will soon be released.

**Comment by a60wattfish** [comment]
Updated to 3.0 and tested. Very nice update and this works as I would like, thanks!
