### ISSUE TITLE
[Feature Request] Add Shortcuts support for opening URLs

### ISSUE THREAD

**Issue by a60wattfish** [snowhaze/SnowHaze-iOS#13]
Would it be possible to add support for opening URLs using the Shortcuts Actions in iOS?

I have shortcuts in place for sending URLs to Safari and Chrome, which I use for quickly opening pages between different browsers using the Share menu. I would like to be able to do the same with SnowHaze, which would ideally make it open a URL in a new tab using the default settings.

I'm assuming the new iOS 14 feature for changing the default browser will use a similar feature.

**Comment by snowhaze** [comment]
Please check out the Shortcut under the following link: https://www.icloud.com/shortcuts/168981948d2a49a797db5e398e4b71be
It allows to open any link in SnowHaze from the share menu of iOS.

**Comment by a60wattfish** [comment]
Just tested and that works perfectly. Thanks.
