### ISSUE TITLE
[Feature Request] Amnesia for tabs

### ISSUE THREAD

**Issue by a60wattfish** [snowhaze/SnowHaze-iOS#14]
This is basically a request for a number of features from DuckDuckGo and FireFox Focus in relation to keeping tabs open. I'd probably delete both of them from my phone if this was implemented.

Have a button on the tab screen to close all of the open tabs. This may already be a feature, however I can't seem to find it anywhere.

Options for making SnowHaze forget about all open tabs at certain points such as:

- When SnowHaze loses focus
- When SnowHaze is closed
- If SnowHaze is in the background/unused for a certain length of time
- If the screen is locked when SnowHaze is in use
- If an incorrect passcode is entered

**Comment by snowhaze** [comment]
We included such a feature into the next version that is coming soon. Long pressing on the tabs icon will open buttons to "Close current tab" and "Close all tabs".
