### ISSUE TITLE
[Feature Request] Add option to open link in background tab

### ISSUE THREAD

**Issue by idunno101** [snowhaze/SnowHaze-iOS#17]
Safari has the feature of holding on a link and then tapping "Open in Background" to put the link on a new tab to read later.
Snowhaze has the ability to open a link in a new tab but it immediately switches to that tab.

**Comment by snowhaze** [comment]
Implemented in version 3.1 (29e381773dd3afb7ee8d070a61f75b750cc3b3c4).
