### ISSUE TITLE
Default browser option

### ISSUE THREAD

**Issue by briansix** [snowhaze/SnowHaze-iOS#18]
Set Snowhaze as default browser in iOS 14

**Comment by snowhaze** [comment]
We're currently in Apple's review process to get approved as default browser. We hope to be through it very soon.

**Comment by snowhaze** [comment]
Implemented in version 3.1 (29e381773dd3afb7ee8d070a61f75b750cc3b3c4)
Keep in mind that it will only work on builds signed by SnowHaze, i.e. downloaded from the App Store. The corresponding portion of the code was therefore commented in this repo.
