### ISSUE TITLE
Constant internet traffic 

### ISSUE THREAD

**Issue by Thyname** [snowhaze/SnowHaze-iOS#2]
Snowhaze keeps using internet all the time, as seen by the icon in iOS ( https://postimg.cc/image/5w4uyh5ep/ ) and by the light in the router that keeps flashing.
Sometimes just by entering its settings it starts to use the web non-stop (in this case it isn't all the time and I have yet to see which option causes this).
From what I have observed, when it starts with this behaviour it won't stop using the net unless it's closed. I liked many things in this browser but I don't use it because of this.
iPad 2 iOS 9.3.5

**Comment by snowhaze** [comment]
Hi Thyname, thanks for your message! I assume that you built it yourself. The open source version here on Github doesn't contain the decryption key for the database that is loaded into the app. Therefore, the app constantly tries to load a database, that cannot be decrypted. I suggest that you keep the setting "Auto-Update Site Lists" to off. You will only have limited site lists, but no longer the problem where it is constantly loading. I hope this helps, Best!

**Comment by Thyname** [comment]
Thanks for answering. Sure enough, it was trying to fetch the list.
I didn't build it, it's just the free version.

I had suspected that was the reason but maybe I thought it was too obvious and didn't turn it off.
As I said, I like snowhaze and now I'll use it more often to evaluate better. Also the effect of having a list that's fixed.
Don't want to take your time but the list actually covers which cases (ads, phishing etc.)?
Thanks.

**Comment by snowhaze** [comment]
Hi, the lists contained are the following:
-    Malicious sites
-    Ads
-    Trackers
-    Cross site scripting (XSS)
-    Known sites to support HTTPS
-    Private sites
-    Phishing sites
-    Content blockers
-    Unnecessary URL parameters
The lists are never perfect but we try to keep them as complete and up to date as we can. 
Best regards
