### ISSUE TITLE
Some websites go blank after loading

### ISSUE THREAD

**Issue by idunno101** [snowhaze/SnowHaze-iOS#20]
Some websites (such as reddit.com) become a blank white page a second after loading. I've tried changing the ad, canvas, and script blocking but the outcome is the same each time.
I attached Reddit_Snowhaze which shows the syslog while loading reddit.com 
The error seems to occur around line 50.
I also attached Reddit_Safari which shows its syslog while loading reddit.

[Reddit_Safari.txt](https://github.com/snowhaze/SnowHaze-iOS/files/5419932/Reddit_Safari.txt)
[Reddit_Snowhaze.txt](https://github.com/snowhaze/SnowHaze-iOS/files/5419933/Reddit_Snowhaze.txt)

**Comment by snowhaze** [comment]
We are still working on this issue that came with iOS 14 and the new WebKit API. In the meantime, allowing JavaScript per tab or globally should be a good workaround.

**Comment by snowhaze** [comment]
Solved with version 3.1.1
