### ISSUE TITLE
app filtering

### ISSUE THREAD

**Issue by boistordu** [snowhaze/SnowHaze-iOS#4]
Hi,

I don't know if it's possible with the framework of iOS but it would be great if we could maybe make a list of exception of apps who doesn't need to go through the vpn.

Reason: Some internet data package are unlimited for some app and you don't need necessarily that kind of privacy for that since you are logged into them with you identity anyway
+ specifics apps or website doesn't support VPN. netflix among other things.

**Comment by snowhaze** [comment]
Hi, 
Thanks for your comment. On iOS the VPN runs system-wide and the user unfortunately doesn't have the possibility to customize the network for apps. I think Android offers more flexibility there. On iOS Apple chooses which apps are using the VPN. It is however not transparent how they choose; e.g. while all non-Apple apps use the VPN, Apple's iMessage or personal hotspot don't go over the VPN. 

I personally have the same problem with my network provider not recognizing certain "unlimited data" services. While you can't hide what you consume with the service itself, you might still want to hide it from your internet service provider.

Netflix seems to handle our VPNs very differently. They recognize and block most of them. Lately, the US VPN changed a few time from being blocked to allow connections and block again.

**Comment by boistordu** [comment]
Thank you for your answer,
So yeah there is still a lot of ground to cover for iOS to be mature enough to be that granular in their framework.
Is a workaround like "deactivate the vpn completely when a specific app is active possible? Like if you launch netflix for example ? Or even that would cause problems? 

Yeah you can't have both world, and to hide it from the ISP the more important solution to me has always been the use of https by the devs in their apps, like the switch of Tinder a few months ago from http to https.  

D you have any insight about why a vpn like nordvpn is authorized by netflix and not yours for example? Do they have an agreement with netflix or do they have a soft service on their network to trick netflix that we don't know about?

**Comment by snowhaze** [comment]
The only way I can think of is selectively turning off the VPN when you want to use these services. This instantly changes back your IP as you can verify e.g. on https://ipleak.net. 
Nobody really knows how Netflix and other services block the access. I suppose it must be a combination of IP blocking, white- and blacklisting and other criteria. Large VPN services like Nord VPN have many different IP addresses for each location and they constantly add more. The services are a bit slower in catching up and adding the new IP addresses to their block list. Our IPs were not blocked for quite some time and then some of them got blocked and unblocked again. I couldn't figure our what the logic is behind it.
