### ISSUE TITLE
dns request under dnscrypt

### ISSUE THREAD

**Issue by boistordu** [snowhaze/SnowHaze-iOS#5]
Hi,

Would it be possible to add a client-side dnscrypt in your browser for those who wouldn't use your VPN? 
you can read a discussion about it in https://github.com/jedisct1/dnscrypt-proxy/issues/42 
I'm sure that if we help generalize it more and more app would want it.

SideNote: is the filter lists only client-side? or do you have a service like pi-hole on your network? Did you think about putting a service like it in place on your Vpn network? Lie we would be able to choose between 2 vpn server in your network through a simple button.

**Comment by snowhaze** [comment]
Thank you for the suggestion. We will look into it. As for the lists they are solely on the client side. Managing the list on the servers for all users is not possible with our anonymous protocol since the server doesn't know the users.
