### ISSUE TITLE
[Feature Request] Add Desktop User Agent to Shield menu

### ISSUE THREAD

**Issue by compl3x** [snowhaze/SnowHaze-iOS#6]
One of the most useful feature that’s missing in the app is the ability to change the user agent of the page. The only way i found is creating a new tab that has desktop user agent.

To make the usage more efficient, taking the same option in new tab to the shield’s menu on the address bar. This would make it even more efficient than safari placement.
Hope what i mentioned is clear.

**Comment by snowhaze** [comment]
Hi, thank you for your request. The user agent has to be set when the tab is created. It is not possible to change the user of an existing tab. You mentioned correctly that creating a new tab with settings is the only possibility to do it. You could then drag and drop another tab onto it to open the same page in your new tab. This should not take too much time. The downside is that you would have to do it every time you visit that site.
