### ISSUE TITLE
[Feature Request] Implement Apple Wallet

### ISSUE THREAD

**Issue by dddjjjbbb** [snowhaze/SnowHaze-iOS#7]
I'm wondering if implementing support for apple wallet would be considered? Apple docs are [here](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/index.html#//apple_ref/doc/uid/TP40012195).

**Comment by snowhaze** [comment]
How do you imagine wallet support in SnowHaze? Would you like to export tickets, cards, etc. from SnowHaze into your wallet? I will be able to better answer your question with these additional information.
