### ISSUE TITLE
[Feature Request] Open links in a new tab

### ISSUE THREAD

**Issue by ghost** [snowhaze/SnowHaze-iOS#8]
Give users the ability to hold-tap a link and give the option to open that link in a new tab, preferably in the background.

**Comment by snowhaze** [comment]
You can open links in new tabs via the 3D Touch menu. Simply force press the link and choose "Open in New Tab". This will directly open  the link in a new tab. With iOS 13, all devices will be able to use the force press options.

**Comment by snowhaze** [comment]
It works now on all devices running iOS 13.
